import crypto from'node:crypto';import{afterAll,beforeAll,describe,expect,it}from'vitest';import{PrismaClient}from'@prisma/client';import{appendAudit,canonicalJson,sha256,verifyAudit}from'../lib/governance/audit';import{requireProductionConfiguration}from'../lib/governance/policy';import{verifyWebhook}from'../lib/governance/providers';import{addVersion,applyEsignEvent,auditStatus,createDocument,documentDetail,exportEvidence,grantAccess,listDocuments,purgeDocument,redactDocument,reviewDocument,revokeAccess,runProvider,updateRetention}from'../lib/governance/service';
const db=new PrismaClient();const id=()=>crypto.randomUUID();const ids={owner:id(),reviewer:id(),editor:id(),viewer:id(),outsider:id(),client:id(),matter:id(),otherMatter:id()};const effective='2026-07-19T12:00:00.000Z';let documentId:string,versionHash:string;
async function rejectsCode(work:Promise<unknown>,code:string){await expect(work).rejects.toMatchObject({code})}
beforeAll(async()=>{await db.$executeRawUnsafe(`TRUNCATE TABLE "ProviderWebhookEvent","DocumentExport","DocumentProviderOperation","DocumentReview","DocumentVersion","GovernanceAuditEvent","CaseAccess","Document","CourtFiling","Message","MessageThread","Invoice","TimeEntry","Task","Case","IntakeForm","Client","User","AuthoritativeTemplate" CASCADE`);await db.user.createMany({data:[{id:ids.owner,email:'owner@test.local',hashedPassword:'x',name:'Owner Lawyer',role:'LAWYER'},{id:ids.reviewer,email:'reviewer@test.local',hashedPassword:'x',name:'Review Lawyer',role:'LAWYER'},{id:ids.editor,email:'editor@test.local',hashedPassword:'x',name:'Editor',role:'STAFF'},{id:ids.viewer,email:'viewer@test.local',hashedPassword:'x',name:'Viewer',role:'STAFF'},{id:ids.outsider,email:'outside@test.local',hashedPassword:'x',name:'Outside',role:'STAFF'}]});await db.client.create({data:{id:ids.client,firstName:'Client',lastName:'One',email:'client@test.local',phone:'tokenized-contact'}});await db.case.createMany({data:[{id:ids.matter,title:'Matter One',description:'governed',clientId:ids.client,responsibleLawyerId:ids.owner,practiceArea:'CIVIL'},{id:ids.otherMatter,title:'Other Matter',description:'isolated',clientId:ids.client,responsibleLawyerId:ids.reviewer,practiceArea:'BUSINESS'}]});await db.caseAccess.createMany({data:[{caseId:ids.matter,userId:ids.reviewer,role:'COUNSEL',privilegedAccess:true},{caseId:ids.matter,userId:ids.editor,role:'EDITOR',privilegedAccess:false},{caseId:ids.matter,userId:ids.viewer,role:'VIEWER',privilegedAccess:false}]})});afterAll(()=>db.$disconnect());
describe.sequential('governed legal documents',()=>{
it('canonicalizes provenance deterministically',()=>{expect(canonicalJson({b:2,a:1})).toBe(canonicalJson({a:1,b:2}));expect(sha256('evidence')).toMatch(/^[0-9a-f]{64}$/)});
it('fails closed on incomplete production configuration',()=>{const env=process.env as unknown as Record<string,string|undefined>;const priorMode=env.NODE_ENV;const priorDatabase=env.DATABASE_URL;env.NODE_ENV='production';delete env.DATABASE_URL;expect(requireProductionConfiguration).toThrow(/Production requires/);if(priorMode===undefined)delete env.NODE_ENV;else env.NODE_ENV=priorMode;if(priorDatabase===undefined)delete env.DATABASE_URL;else env.DATABASE_URL=priorDatabase});
it('creates a matter-scoped document with immutable version provenance',async()=>{const created=await createDocument(ids.editor,{caseId:ids.matter,title:'Engagement',docType:'CONTRACT',content:'Client secret and agreed terms',provenanceType:'HUMAN',sourceReference:'intake:verified-1',jurisdiction:'NY',effectiveDate:effective,privileged:false});documentId=created.id;versionHash=created.versions[0].contentHash;expect(created.versions[0]).toMatchObject({version:1,requiresLegalReview:true,contentHash:sha256('Client secret and agreed terms')})});
it('binds authoritative provenance to template content, jurisdiction, and effective date',async()=>{const content='Court-issued filing template';const template=await db.authoritativeTemplate.create({data:{sourceSystem:'court-test',externalId:'template-1',title:'Court Form',jurisdiction:'NY',effectiveFrom:new Date('2026-01-01T00:00:00.000Z'),contentHash:sha256(content),providerEvidence:{providerId:'test'}}});const created=await createDocument(ids.editor,{caseId:ids.matter,title:'Court form',docType:'FORM',content,provenanceType:'AUTHORITATIVE_TEMPLATE',sourceReference:'court-test:template-1',templateId:template.id,jurisdiction:'NY',effectiveDate:effective,privileged:false});expect(created.versions[0].templateId).toBe(template.id);await rejectsCode(createDocument(ids.editor,{caseId:ids.matter,title:'Altered form',docType:'FORM',content:'altered',provenanceType:'AUTHORITATIVE_TEMPLATE',sourceReference:'court-test:template-1',templateId:template.id,jurisdiction:'NY',effectiveDate:effective,privileged:false}),'template_invalid')});
it('enforces optimistic document version conflicts',async()=>{await rejectsCode(addVersion(ids.editor,documentId,{content:'changed',expectedVersion:9,provenanceType:'HUMAN',sourceReference:'edit',jurisdiction:'NY',effectiveDate:effective}),'version_conflict')});
it('requires complete AI model and prompt provenance',async()=>{await expect(addVersion(ids.editor,documentId,{content:'generated',expectedVersion:1,provenanceType:'AI_DRAFT',sourceReference:'model-run-1',jurisdiction:'NY',effectiveDate:effective})).rejects.toThrow(/model and prompt hash/)});
it('redacts every exact occurrence into a new version',async()=>{const version=await redactDocument(ids.editor,documentId,{expectedVersion:1,terms:['Client secret'],jurisdiction:'NY',effectiveDate:effective});expect(version.version).toBe(2);expect(version.content).toContain('[REDACTED]');expect(version.content).not.toContain('Client secret')});
it('blocks privileged material from unprivileged matter viewers',async()=>{const privileged=await createDocument(ids.owner,{caseId:ids.matter,title:'Counsel strategy',docType:'BRIEF',content:'privileged',provenanceType:'HUMAN',sourceReference:'counsel:1',jurisdiction:'NY',effectiveDate:effective,privileged:true});await rejectsCode(documentDetail(ids.viewer,privileged.id),'privileged_access_denied')});
it('requires a separate qualified counsel reviewer',async()=>{await expect(reviewDocument(ids.editor,documentId,{version:2,decision:'APPROVED',jurisdiction:'NY',effectiveDate:effective,sourceValidated:true,notes:'self'})).rejects.toMatchObject({code:'matter_access_denied'});const own=await createDocument(ids.owner,{caseId:ids.matter,title:'Owner draft',docType:'LETTER',content:'draft',provenanceType:'HUMAN',sourceReference:'owner:1',jurisdiction:'NY',effectiveDate:effective,privileged:false});await rejectsCode(reviewDocument(ids.owner,own.id,{version:1,decision:'APPROVED',jurisdiction:'NY',effectiveDate:effective,sourceValidated:true,notes:'self approval'}),'separation_of_duties')});
it('validates review jurisdiction, effective date, and authoritative source',async()=>{await rejectsCode(reviewDocument(ids.reviewer,documentId,{version:2,decision:'APPROVED',jurisdiction:'CA',effectiveDate:effective,sourceValidated:true,notes:'wrong jurisdiction'}),'review_scope_mismatch');await rejectsCode(reviewDocument(ids.reviewer,documentId,{version:2,decision:'APPROVED',jurisdiction:'NY',effectiveDate:effective,sourceValidated:false,notes:'source not checked'}),'source_not_validated')});
it('records independent approval and exports verifiable evidence',async()=>{const review=await reviewDocument(ids.reviewer,documentId,{version:2,decision:'APPROVED',jurisdiction:'NY',effectiveDate:effective,sourceValidated:true,notes:'Compared with authoritative source'});expect(review.decision).toBe('APPROVED');const exported=await exportEvidence(ids.viewer,documentId);expect(exported.manifestHash).toMatch(/^[0-9a-f]{64}$/);expect(exported.manifest).toMatchObject({documentId,version:2})});
it('fails external providers closed and persists failure evidence',async()=>{delete process.env.OCR_API_URL;delete process.env.OCR_API_TOKEN;await rejectsCode(runProvider(ids.editor,documentId,{kind:'OCR',idempotencyKey:'ocr-request-001',payload:{objectKey:'vault/object'}}),'provider_unavailable');const operation=await db.documentProviderOperation.findFirstOrThrow({where:{documentId,kind:'OCR'}});expect(operation.state).toBe('FAILED');expect(operation.failureCode).toBe('provider_unavailable')});
it('detects provider idempotency conflicts',async()=>{await rejectsCode(runProvider(ids.editor,documentId,{kind:'OCR',idempotencyKey:'ocr-request-001',payload:{objectKey:'different'}}),'idempotency_conflict')});
it('verifies timestamped signature callbacks against exact bytes',()=>{process.env.ESIGN_WEBHOOK_SECRET='test-esign-secret-longer-than-thirty-two-characters';const raw='{"eventId":"one"}';const timestamp=String(Math.floor(Date.now()/1000));const signature=crypto.createHmac('sha256',process.env.ESIGN_WEBHOOK_SECRET).update(`${timestamp}.${raw}`).digest('hex');expect(verifyWebhook(raw,timestamp,signature)).toBe(true);expect(verifyWebhook(raw+'x',timestamp,signature)).toBe(false)});
it('records signer failure callbacks idempotently and rejects conflicting replays',async()=>{const operation=await db.documentProviderOperation.create({data:{documentId,kind:'ESIGN',idempotencyKey:'esign-test-001',state:'PENDING',provider:'esign-test',requestHash:sha256('request'),attempts:1}});const event={eventId:'esign-event-001',operationId:operation.id,state:'failed' as const,externalId:'envelope-1',failureCode:'signer_declined'};const applied=await applyEsignEvent(event);expect(applied.operation).toMatchObject({state:'FAILED',failureCode:'signer_declined'});expect(await applyEsignEvent(event)).toEqual({replay:true});await rejectsCode(applyEsignEvent({...event,externalId:'envelope-changed'}),'idempotency_conflict')});
it('revokes matter access immediately',async()=>{await revokeAccess(ids.owner,ids.matter,ids.viewer);await rejectsCode(documentDetail(ids.viewer,documentId),'matter_access_denied');await grantAccess(ids.owner,ids.matter,{userId:ids.viewer,role:'VIEWER',privilegedAccess:false});expect((await documentDetail(ids.viewer,documentId))?.id).toBe(documentId)});
it('isolates document lists from unrelated users and matters',async()=>{expect(await listDocuments(ids.outsider)).toEqual([]);expect((await listDocuments(ids.viewer)).some(item=>item.id===documentId)).toBe(true)});
it('blocks retention purge under legal hold',async()=>{await updateRetention(ids.owner,documentId,{retentionUntil:'2020-01-01T00:00:00.000Z',legalHold:true,legalHoldReason:'active discovery'});await rejectsCode(purgeDocument(ids.owner,documentId),'retention_blocked')});
it('purges payloads only after hold release and retention expiry',async()=>{await updateRetention(ids.owner,documentId,{retentionUntil:'2020-01-01T00:00:00.000Z',legalHold:false,legalHoldReason:null});expect(await purgeDocument(ids.owner,documentId)).toMatchObject({purged:true,evidenceRetained:true});const versions=await db.documentVersion.findMany({where:{documentId}});expect(versions.every(version=>version.content===null)).toBe(true);expect(versions.find(version=>version.version===1)?.contentHash).toBe(versionHash)});
it('maintains a verifiable hash-chained audit after content purge',async()=>{expect((await auditStatus(ids.owner,ids.matter)).valid).toBe(true);expect(await verifyAudit(db,ids.matter)).toBe(true)});
it('rejects direct mutation and deletion of evidence rows',async()=>{const audit=await db.governanceAuditEvent.findFirstOrThrow({where:{caseId:ids.matter}});await expect(db.$executeRawUnsafe(`UPDATE "GovernanceAuditEvent" SET "action"='tampered' WHERE "id"=$1`,audit.id)).rejects.toThrow(/append-only/);const version=await db.documentVersion.findFirstOrThrow({where:{documentId}});await expect(db.$executeRawUnsafe(`UPDATE "DocumentVersion" SET "sourceReference"='tampered' WHERE "id"=$1`,version.id)).rejects.toThrow(/immutable/)});
it('serializes concurrent audit appends without duplicate sequence numbers',async()=>{await Promise.all([1,2,3].map(value=>db.$transaction(tx=>appendAudit(tx,{caseId:ids.otherMatter,actorId:ids.reviewer,action:'concurrent.test',details:{value}}))));const events=await db.governanceAuditEvent.findMany({where:{caseId:ids.otherMatter},orderBy:{sequence:'asc'}});expect(events.map(event=>Number(event.sequence))).toEqual([1,2,3]);expect(await verifyAudit(db,ids.otherMatter)).toBe(true)});
});
