import crypto from 'node:crypto';
import { ProviderOperationKind } from '@prisma/client';
import { GovernanceError } from './policy';

const config: Record<ProviderOperationKind,{url:string;token:string}> = {
  OCR:{url:'OCR_API_URL',token:'OCR_API_TOKEN'}, ESIGN:{url:'ESIGN_API_URL',token:'ESIGN_API_TOKEN'}, STORAGE:{url:'STORAGE_API_URL',token:'STORAGE_API_TOKEN'},
  FILING:{url:'FILING_API_URL',token:'FILING_API_TOKEN'}, TEMPLATE:{url:'TEMPLATE_API_URL',token:'TEMPLATE_API_TOKEN'}, LEGAL_DRAFT:{url:'LEGAL_DRAFT_API_URL',token:'LEGAL_DRAFT_API_TOKEN'},
};
export async function callProvider(kind:ProviderOperationKind,payload:unknown,idempotencyKey:string){const names=config[kind];const endpoint=process.env[names.url];const token=process.env[names.token];if(!endpoint||!token)throw new GovernanceError(503,`${kind.toLowerCase()} provider is not configured`,'provider_unavailable');const url=new URL(endpoint);if(process.env.NODE_ENV==='production'&&url.protocol!=='https:')throw new GovernanceError(503,'Production providers require HTTPS','provider_configuration');const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),8_000);try{const response=await fetch(url,{method:'POST',signal:controller.signal,headers:{authorization:`Bearer ${token}`,'content-type':'application/json','idempotency-key':idempotencyKey},body:JSON.stringify(payload)});if(!response.ok)throw new GovernanceError(502,`${kind.toLowerCase()} provider returned ${response.status}`,'provider_failed');if(Number(response.headers.get('content-length')||0)>2_000_000)throw new GovernanceError(502,'Provider response exceeded the evidence limit','provider_invalid_response');const raw=await response.text();if(Buffer.byteLength(raw)>2_000_000)throw new GovernanceError(502,'Provider response exceeded the evidence limit','provider_invalid_response');const body=JSON.parse(raw);if(!body||typeof body!=='object'||typeof body.id!=='string')throw new GovernanceError(502,'Provider response lacked an evidence id','provider_invalid_response');return body as Record<string,unknown>&{id:string};}catch(error){if(error instanceof GovernanceError)throw error;throw new GovernanceError(502,`${kind.toLowerCase()} provider request failed`,'provider_failed');}finally{clearTimeout(timeout)}}
export function verifyWebhook(raw:string,timestamp:string,signature:string){const seconds=Number(timestamp);if(!Number.isFinite(seconds)||Math.abs(Date.now()/1000-seconds)>300)return false;const secret=process.env.ESIGN_WEBHOOK_SECRET;if(!secret||secret.length<32)return false;const expected=crypto.createHmac('sha256',secret).update(`${timestamp}.${raw}`).digest('hex');const a=Buffer.from(signature);const b=Buffer.from(expected);return a.length===b.length&&crypto.timingSafeEqual(a,b)}
