import { MatterAccessRole, Prisma, PrismaClient, ProviderOperationKind, ProvenanceType, ReviewDecision, UserRole } from '@prisma/client';
import { z } from 'zod';
import prisma from '../prisma';
import { appendAudit, canonicalJson, sha256, verifyAudit } from './audit';
import { callProvider } from './providers';
import { GovernanceError, requireAccess } from './policy';

const versionInput=z.object({content:z.string().min(1).max(2_000_000),expectedVersion:z.number().int().positive().optional(),provenanceType:z.nativeEnum(ProvenanceType),sourceReference:z.string().min(1).max(500),templateId:z.string().uuid().nullable().optional(),jurisdiction:z.string().min(2).max(120),effectiveDate:z.coerce.date(),generatedModel:z.string().max(160).nullable().optional(),promptHash:z.string().regex(/^[0-9a-f]{64}$/).nullable().optional()});
const documentInput=versionInput.omit({expectedVersion:true}).extend({caseId:z.string().uuid(),title:z.string().min(1).max(240),docType:z.enum(['PLEADING','CONTRACT','LETTER','MOTION','BRIEF','FORM','EVIDENCE','OTHER']),privileged:z.boolean().default(false)});
function parsed<T>(schema:z.ZodType<T>,value:unknown){const result=schema.safeParse(value);if(!result.success)throw new GovernanceError(400,result.error.issues.map(i=>`${i.path.join('.')}: ${i.message}`).join('; '),'validation_failed');return result.data}
async function validateTemplate(tx:Prisma.TransactionClient,input:z.infer<typeof versionInput>){if(input.provenanceType!=='AUTHORITATIVE_TEMPLATE')return;if(!input.templateId)throw new GovernanceError(400,'Authoritative template provenance requires templateId');const template=await tx.authoritativeTemplate.findUnique({where:{id:input.templateId}});if(!template)throw new GovernanceError(400,'Authoritative template not found');if(template.jurisdiction!==input.jurisdiction||input.effectiveDate<template.effectiveFrom||(template.effectiveUntil&&input.effectiveDate>template.effectiveUntil)||sha256(input.content)!==template.contentHash)throw new GovernanceError(409,'Template content, jurisdiction, or effective date is invalid','template_invalid')}
async function documentForAccess(db:PrismaClient|Prisma.TransactionClient,actorId:string,documentId:string,minimum:MatterAccessRole){const document=await db.document.findUnique({where:{id:documentId}});if(!document)throw new GovernanceError(404,'Document not found','not_found');await requireAccess(db,actorId,document.caseId,minimum,document.privileged);return document}

export async function createDocument(actorId:string,value:unknown){const input=parsed(documentInput,value);return prisma.$transaction(async tx=>{await requireAccess(tx,actorId,input.caseId,MatterAccessRole.EDITOR,input.privileged);await validateTemplate(tx,input);const hash=sha256(input.content);const document=await tx.document.create({data:{caseId:input.caseId,title:input.title,docType:input.docType,content:input.content,privileged:input.privileged,currentVersion:1,versions:{create:{version:1,content:input.content,contentHash:hash,provenanceType:input.provenanceType,sourceReference:input.sourceReference,templateId:input.templateId||null,jurisdiction:input.jurisdiction,effectiveDate:input.effectiveDate,generatedModel:input.generatedModel||null,promptHash:input.promptHash||null,requiresLegalReview:true,authorId:actorId}}},include:{versions:true}});await appendAudit(tx,{caseId:input.caseId,documentId:document.id,actorId,action:'document.created',details:{version:1,contentHash:hash,provenanceType:input.provenanceType,sourceReference:input.sourceReference,privileged:input.privileged}});return document})}

export async function addVersion(actorId:string,documentId:string,value:unknown){const input=parsed(versionInput,value);return prisma.$transaction(async tx=>{const document=await documentForAccess(tx,actorId,documentId,MatterAccessRole.EDITOR);if(input.expectedVersion!==document.currentVersion)throw new GovernanceError(409,'Document has a newer version','version_conflict');await validateTemplate(tx,input);if(input.provenanceType==='AI_DRAFT'&&(!input.generatedModel||!input.promptHash))throw new GovernanceError(400,'AI drafts require model and prompt hash provenance');const next=document.currentVersion+1;const hash=sha256(input.content);const version=await tx.documentVersion.create({data:{documentId,version:next,content:input.content,contentHash:hash,provenanceType:input.provenanceType,sourceReference:input.sourceReference,templateId:input.templateId||null,jurisdiction:input.jurisdiction,effectiveDate:input.effectiveDate,generatedModel:input.generatedModel||null,promptHash:input.promptHash||null,requiresLegalReview:true,authorId:actorId}});await tx.document.update({where:{id:documentId},data:{content:input.content,currentVersion:next}});await appendAudit(tx,{caseId:document.caseId,documentId,actorId,action:'document.version_created',details:{version:next,contentHash:hash,provenanceType:input.provenanceType,sourceReference:input.sourceReference}});return version})}

export async function redactDocument(actorId:string,documentId:string,value:unknown){const input=parsed(z.object({expectedVersion:z.number().int().positive(),terms:z.array(z.string().min(1)).min(1).max(100),jurisdiction:z.string().min(2),effectiveDate:z.coerce.date()}),value);const document=await documentForAccess(prisma,actorId,documentId,MatterAccessRole.EDITOR);let content=document.content||'';for(const term of input.terms)content=content.split(term).join('[REDACTED]');if(content===document.content)throw new GovernanceError(409,'No requested redaction term was present','redaction_no_match');return addVersion(actorId,documentId,{content,expectedVersion:input.expectedVersion,provenanceType:'REDACTION',sourceReference:`redaction:${sha256(canonicalJson([...input.terms].sort()))}`,jurisdiction:input.jurisdiction,effectiveDate:input.effectiveDate})}

export async function reviewDocument(actorId:string,documentId:string,value:unknown){const input=parsed(z.object({version:z.number().int().positive(),decision:z.nativeEnum(ReviewDecision),jurisdiction:z.string().min(2).max(120),effectiveDate:z.coerce.date(),sourceValidated:z.boolean(),notes:z.string().min(3).max(2000)}),value);return prisma.$transaction(async tx=>{const document=await documentForAccess(tx,actorId,documentId,MatterAccessRole.COUNSEL);const actor=await tx.user.findUnique({where:{id:actorId}});if(!actor||(actor.role!==UserRole.LAWYER&&actor.role!==UserRole.ADMIN))throw new GovernanceError(403,'Licensed counsel or an administrator must review legal content','counsel_required');if(document.currentVersion!==input.version)throw new GovernanceError(409,'Only the current version can be reviewed','version_conflict');const version=await tx.documentVersion.findUnique({where:{documentId_version:{documentId,version:input.version}}});if(!version)throw new GovernanceError(404,'Version not found');if(version.authorId===actorId)throw new GovernanceError(409,'The author cannot approve their own version','separation_of_duties');if(input.jurisdiction!==version.jurisdiction||input.effectiveDate.getTime()!==version.effectiveDate.getTime())throw new GovernanceError(409,'Review jurisdiction and effective date must match the version','review_scope_mismatch');if(input.decision==='APPROVED'&&!input.sourceValidated)throw new GovernanceError(409,'Approval requires authoritative source validation','source_not_validated');const review=await tx.documentReview.create({data:{documentId,documentVersionId:version.id,reviewerId:actorId,decision:input.decision,jurisdiction:input.jurisdiction,effectiveDate:input.effectiveDate,sourceValidated:input.sourceValidated,notes:input.notes}});await appendAudit(tx,{caseId:document.caseId,documentId,actorId,action:`document.review_${input.decision.toLowerCase()}`,details:{version:input.version,jurisdiction:input.jurisdiction,effectiveDate:input.effectiveDate.toISOString(),sourceValidated:input.sourceValidated}});return review})}

export async function grantAccess(actorId:string,caseId:string,value:unknown){const input=parsed(z.object({userId:z.string().uuid(),role:z.nativeEnum(MatterAccessRole),privilegedAccess:z.boolean().default(false)}),value);return prisma.$transaction(async tx=>{await requireAccess(tx,actorId,caseId,MatterAccessRole.OWNER);await tx.user.findFirstOrThrow({where:{id:input.userId,active:true}});const access=await tx.caseAccess.upsert({where:{caseId_userId:{caseId,userId:input.userId}},create:{caseId,userId:input.userId,role:input.role,privilegedAccess:input.privilegedAccess},update:{role:input.role,privilegedAccess:input.privilegedAccess,revokedAt:null}});await appendAudit(tx,{caseId,actorId,action:'matter.access_granted',details:{userId:input.userId,role:input.role,privilegedAccess:input.privilegedAccess}});return access})}
export async function revokeAccess(actorId:string,caseId:string,userId:string){return prisma.$transaction(async tx=>{await requireAccess(tx,actorId,caseId,MatterAccessRole.OWNER);if(actorId===userId)throw new GovernanceError(409,'Owner cannot revoke current self access');const access=await tx.caseAccess.update({where:{caseId_userId:{caseId,userId}},data:{revokedAt:new Date()}});await appendAudit(tx,{caseId,actorId,action:'matter.access_revoked',details:{userId}});return access})}

export async function updateRetention(actorId:string,documentId:string,value:unknown){const input=parsed(z.object({retentionUntil:z.coerce.date().nullable(),legalHold:z.boolean(),legalHoldReason:z.string().max(1000).nullable()}),value);return prisma.$transaction(async tx=>{const document=await documentForAccess(tx,actorId,documentId,MatterAccessRole.COUNSEL);if(input.legalHold&&!input.legalHoldReason)throw new GovernanceError(400,'Legal hold requires a reason');const updated=await tx.document.update({where:{id:documentId},data:input});await appendAudit(tx,{caseId:document.caseId,documentId,actorId,action:input.legalHold?'document.legal_hold_applied':'document.retention_updated',details:{retentionUntil:input.retentionUntil?.toISOString()||null,legalHold:input.legalHold,legalHoldReason:input.legalHoldReason}});return updated})}
export async function purgeDocument(actorId:string,documentId:string){return prisma.$transaction(async tx=>{const document=await documentForAccess(tx,actorId,documentId,MatterAccessRole.OWNER);if(document.legalHold||!document.retentionUntil||document.retentionUntil>new Date())throw new GovernanceError(409,'Legal hold or unexpired retention prevents purge','retention_blocked');await tx.documentVersion.updateMany({where:{documentId},data:{content:null}});await tx.documentProviderOperation.updateMany({where:{documentId},data:{responseEvidence:Prisma.JsonNull}});await tx.document.update({where:{id:documentId},data:{content:null,storagePath:null,aiSummary:null,title:'Purged retained record'}});await appendAudit(tx,{caseId:document.caseId,documentId,actorId,action:'document.payload_purged',details:{lastVersion:document.currentVersion,retentionUntil:document.retentionUntil.toISOString()}});return{purged:true,evidenceRetained:true}})}

export async function exportEvidence(actorId:string,documentId:string){return prisma.$transaction(async tx=>{const document=await documentForAccess(tx,actorId,documentId,MatterAccessRole.VIEWER);const version=await tx.documentVersion.findUniqueOrThrow({where:{documentId_version:{documentId,version:document.currentVersion}}});const approval=await tx.documentReview.findFirst({where:{documentVersionId:version.id,decision:'APPROVED'},orderBy:{createdAt:'desc'}});if(!approval)throw new GovernanceError(409,'Current version needs legal approval before export','review_required');if(!await verifyAudit(tx,document.caseId))throw new GovernanceError(409,'Audit chain verification failed','audit_invalid');const operations=await tx.documentProviderOperation.findMany({where:{documentId},select:{kind:true,state:true,provider:true,externalId:true,requestHash:true,createdAt:true}});const manifest={documentId,caseId:document.caseId,version:version.version,contentHash:version.contentHash,provenance:{type:version.provenanceType,sourceReference:version.sourceReference,templateId:version.templateId},review:{reviewerId:approval.reviewerId,jurisdiction:approval.jurisdiction,effectiveDate:approval.effectiveDate.toISOString(),sourceValidated:approval.sourceValidated},operations};const manifestHash=sha256(canonicalJson(manifest));const record=await tx.documentExport.create({data:{documentId,version:version.version,manifest:manifest as Prisma.InputJsonValue,manifestHash}});await appendAudit(tx,{caseId:document.caseId,documentId,actorId,action:'document.evidence_exported',details:{exportId:record.id,manifestHash,version:version.version}});return{...record,manifest}})}

export async function runProvider(actorId:string,documentId:string,value:unknown){const input=parsed(z.object({kind:z.nativeEnum(ProviderOperationKind),idempotencyKey:z.string().min(8).max(160),payload:z.record(z.string(),z.unknown())}),value);const document=await documentForAccess(prisma,actorId,documentId,MatterAccessRole.EDITOR);if(['ESIGN','FILING'].includes(input.kind)){const version=await prisma.documentVersion.findUniqueOrThrow({where:{documentId_version:{documentId,version:document.currentVersion}}});const approved=await prisma.documentReview.findFirst({where:{documentVersionId:version.id,decision:'APPROVED'}});if(!approved)throw new GovernanceError(409,'Legal approval is required before signature or filing','review_required')}
  const requestHash=sha256(canonicalJson(input.payload));const prior=await prisma.documentProviderOperation.findUnique({where:{documentId_kind_idempotencyKey:{documentId,kind:input.kind,idempotencyKey:input.idempotencyKey}}});if(prior){if(prior.requestHash!==requestHash)throw new GovernanceError(409,'Idempotency key conflicts with a different request','idempotency_conflict');return prior}const pending=await prisma.documentProviderOperation.create({data:{documentId,kind:input.kind,idempotencyKey:input.idempotencyKey,state:'PENDING',provider:input.kind.toLowerCase(),requestHash,attempts:1}});try{const result=await callProvider(input.kind,input.payload,input.idempotencyKey);return await prisma.$transaction(async tx=>{const updated=await tx.documentProviderOperation.update({where:{id:pending.id},data:{state:'SUCCEEDED',externalId:result.id,responseEvidence:result as Prisma.InputJsonValue}});await appendAudit(tx,{caseId:document.caseId,documentId,actorId,action:`provider.${input.kind.toLowerCase()}_succeeded`,details:{operationId:pending.id,requestHash,externalId:result.id}});return updated})}catch(error){await prisma.$transaction(async tx=>{await tx.documentProviderOperation.update({where:{id:pending.id},data:{state:'FAILED',failureCode:error instanceof GovernanceError?error.code:'provider_failed'}});await appendAudit(tx,{caseId:document.caseId,documentId,actorId,action:`provider.${input.kind.toLowerCase()}_failed`,details:{operationId:pending.id,requestHash,code:error instanceof GovernanceError?error.code:'provider_failed'}})});throw error}}

export async function syncTemplate(actorId:string,value:unknown){const input=parsed(z.object({idempotencyKey:z.string().min(8).max(160),externalId:z.string().min(1).max(240),jurisdiction:z.string().min(2).max(120),effectiveDate:z.coerce.date()}),value);const actor=await prisma.user.findFirst({where:{id:actorId,active:true}});if(!actor||![UserRole.ADMIN,UserRole.LAWYER].includes(actor.role as 'ADMIN'|'LAWYER'))throw new GovernanceError(403,'Counsel or administrator required');const response=await callProvider('TEMPLATE',{externalId:input.externalId,jurisdiction:input.jurisdiction,effectiveDate:input.effectiveDate.toISOString()},input.idempotencyKey);if(typeof response.content!=='string'||typeof response.title!=='string'||typeof response.sourceSystem!=='string'||typeof response.effectiveFrom!=='string')throw new GovernanceError(502,'Template provider response is incomplete','provider_invalid_response');const effectiveFrom=new Date(response.effectiveFrom);const effectiveUntil=typeof response.effectiveUntil==='string'?new Date(response.effectiveUntil):null;if(Number.isNaN(effectiveFrom.getTime())||(effectiveUntil&&Number.isNaN(effectiveUntil.getTime())))throw new GovernanceError(502,'Template provider dates are invalid','provider_invalid_response');return prisma.authoritativeTemplate.upsert({where:{sourceSystem_externalId_effectiveFrom:{sourceSystem:response.sourceSystem,externalId:input.externalId,effectiveFrom}},create:{sourceSystem:response.sourceSystem,externalId:input.externalId,title:response.title,jurisdiction:input.jurisdiction,effectiveFrom,effectiveUntil,contentHash:sha256(response.content),providerEvidence:{providerId:response.id,idempotencyKey:input.idempotencyKey}},update:{title:response.title,effectiveUntil,contentHash:sha256(response.content),providerEvidence:{providerId:response.id,idempotencyKey:input.idempotencyKey}}})}

export async function applyEsignEvent(value:unknown){const input=parsed(z.object({eventId:z.string().min(1).max(200),operationId:z.string().uuid(),state:z.enum(['completed','failed']),externalId:z.string().min(1).max(240),failureCode:z.string().max(120).optional()}),value);const payloadHash=sha256(canonicalJson(input));return prisma.$transaction(async tx=>{const prior=await tx.providerWebhookEvent.findUnique({where:{provider_eventId:{provider:'esign',eventId:input.eventId}}});if(prior){if(prior.payloadHash!==payloadHash)throw new GovernanceError(409,'Webhook event conflicts with prior payload','idempotency_conflict');return{replay:true}}const operation=await tx.documentProviderOperation.findFirst({where:{id:input.operationId,kind:'ESIGN'},include:{document:true}});if(!operation)throw new GovernanceError(404,'Signature operation not found');await tx.providerWebhookEvent.create({data:{provider:'esign',eventId:input.eventId,payloadHash}});const updated=await tx.documentProviderOperation.update({where:{id:operation.id},data:{state:input.state==='completed'?'SUCCEEDED':'FAILED',externalId:input.externalId,failureCode:input.state==='failed'?(input.failureCode||'signer_failed'):null}});await appendAudit(tx,{caseId:operation.document.caseId,documentId:operation.documentId,action:input.state==='completed'?'esign.completed':'esign.failed',details:{operationId:operation.id,eventId:input.eventId,externalId:input.externalId,failureCode:input.failureCode||null}});return{replay:false,operation:updated}})}

export async function auditStatus(actorId:string,caseId:string){await requireAccess(prisma,actorId,caseId,MatterAccessRole.VIEWER);return{valid:await verifyAudit(prisma,caseId)}}

export async function documentDetail(actorId:string,documentId:string){const document=await documentForAccess(prisma,actorId,documentId,MatterAccessRole.VIEWER);return prisma.document.findUnique({where:{id:document.id},include:{case:{include:{client:true,responsibleLawyer:{select:{id:true,name:true}}}},versions:{orderBy:{version:'desc'}},reviews:{orderBy:{createdAt:'desc'}},providerOperations:{orderBy:{createdAt:'desc'}},exports:{orderBy:{createdAt:'desc'}}}})}
export async function listDocuments(actorId:string){const actor=await prisma.user.findFirst({where:{id:actorId,active:true}});if(!actor)throw new GovernanceError(401,'Identity is inactive');return prisma.document.findMany({where:actor.role==='ADMIN'?{}:{case:{OR:[{responsibleLawyerId:actorId},{access:{some:{userId:actorId,revokedAt:null}}}]},OR:[{privileged:false},{case:{OR:[{responsibleLawyerId:actorId},{access:{some:{userId:actorId,revokedAt:null,privilegedAccess:true}}}]}}]},include:{case:{select:{id:true,title:true}},versions:{take:1,orderBy:{version:'desc'},select:{contentHash:true,provenanceType:true,requiresLegalReview:true}}},orderBy:{updatedAt:'desc'}})}
